[package]
name = "challenge37"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
crypto-bigint = "0.5.5"
rand = "0.8.5"
tokio = {version = "1.37.0", features = ["full"] }
tools = { path = "../tools"}
challenge36 = {path = "../challenge36" }