[package]
name = "tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.6.0"
md4 = "0.10.2"
openssl = "0.10.64"
rand = "0.8.5"
rand_core = "0.6.4"
